spring.application.name=mymusicjournal

spring.datasource.url=jdbc:postgresql://localhost:5432/mymusicjournal
spring.datasource.username=postgres
spring.datasource.password=bfm0105@!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080
server.servlet.context-path=/

  app.jwt.secret=your_super_secret_key_that_should_be_at_least_256_bits_long_for_security_reasons_change_this_in_production
  app.jwt.expirationMs=86400000

